### ISSUE TITLE
Parameter 'req' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by mktcode** [mktcode/lib#1]
![Image](https://user-images.githubusercontent.com/6792578/223491641-6ed548d3-fd92-464e-9313-242c3e26643a.png)

https://github.com/mktcode/lib/blob/61aaa309f913dbca070e20317a7a9aae9e6e935d/packages/web3indexer/src/index.ts#L18

What type/interface do I need to use here?

**Comment by mktcode** [comment]
Hey thanks for your comment. How did you find this project? `any` isn't the solution here. Interestingly it looks fine in the [demo](https://github.com/mktcode/lib/blob/master/demo/server/src/web3indexer/index.ts). The screenshot came from [another repo](https://github.com/mktcode/dgame-indexer/blob/master/src/index.ts). Maybe just some config issue. But as far as I understand it should absolutley pick up the correct type. :/

**Comment by RobinRuf** [comment]
Hey, I found this project because u opened an issue. I scroll through all issues a few times per week to help others and find few projects where I can be a contributor haha

Ok.. hmm.. well everytime I use any type for request and response it works perfect if I post the correct data in the correct format (JSON) - so it confuses me that this doesn't work for u.

**Comment by mktcode** [comment]
Well, it would work of course. But it would just silent the Typescript compiler and usually it complains for a good reason. It is just a better developer experience when your IDE can properly inspect all the types. With `any` you don't get auto-completion and all the good stuff. So whenever Typescript complains about something, I tried to really understand the issue and be obedient. :D

> I scroll through all issues a few times per week to help others and find few projects where I can be a contributor haha

That's awesome! If you are also interested in decentralization and web3 and all that, you should probably check out [OpenQ](https://github.com/OpenQDev). Trying to build cool stuff for open source contributors and projects, currently focusing on hackathons. Or maybe the [good-first-web3-issues package](https://github.com/mktcode/lib/tree/master/packages/good-first-web3-issues), running [here](https://gfw3i.mktcode.uber.space/) serving a list of good first issues in web3 orgs on GitHub.

**Comment by RobinRuf** [comment]
Awesome, thank you mate.
I will check out these repos for sure!
